- name: STIG all RHEL hosts
  hosts: all
  become: yes
  tasks:
  - name: Preinstall fapolicyd
    package:
      name: fapolicyd
      state: installed

  - name: Start fapolicyd
    service:
      name: fapolicyd
      state: started
      enabled: yes

  - name: Preconfigure fapolicyd to prevent getting locked out
    lineinfile:
      path: /etc/fapolicyd/fapolicyd.rules
      insertafter: 'allow perm=any uid=0 : dir=/root/.ansible/tmp/'
      line: 'allow perm=any gid=wheel : ftype=text/x-python dir=/home'
    register: fapolicy_rule

  - name: Restart fapolicyd
    service:
      name: fapolicyd
      state: restarted
    when: fapolicy_rule.changed

  - name: Ensure users are in the wheel group
    user:
      name: '{{ item }}'
      append: yes
      groups: wheel
    loop: '{{ users_to_add_to_wheel }}'
    vars:
      users_to_add_to_wheel:
      - ec2-user
      - '{{ ansible_env["SUDO_USER"] }}'

  - name: Include the STIG role for these hosts
    include_role:
      name: redhatofficial.rhel{{ ansible_distribution_major_version }}_stig
    when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version in ["7", "8"]
