- name: STIG all RHEL hosts
  hosts: all
  become: yes
  tasks:
  - name: Include the STIG role for these hosts
    include_role:
      name: redhatofficial.rhel{{ ansible_distribution_major_version }}_stig
    when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version in ["7", "8"]
